# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main, staging]

jobs:
  build:
    if: github.event_name == 'push'
    environment: 
      name: Develop
      url: https://pokemon-develop.netlify.app/
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies with a clean slate
        run: npm install
      - name: Build
        run: npm run build --if-present
  
  test:
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install dependencies with a clean slate
        run: npm install
      - name: Run the tests
        run: npm test
  
  stage:
    if: github.base_ref == 'staging'
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: https://pokemon-staging.netlify.app/
    steps:
      - name: Staging
        run: echo "Staging"
  
  deploy:
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: https://pokemon-ragnarok.netlify.app/
    steps:
      - name: Deploy
        run: echo "Deploying"
    
